const CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRJH1dw4bmYwPC5Yxf8zKEeQvOb7aWKnxoZ-XTuPfBn_tOVyPQjQdE-kcBcOGRzQ-Iy_1FaDvGoPjV_/pub?gid=622475547&single=true&output=csv";
let chartInstance=null;
document.addEventListener("DOMContentLoaded",()=>{loadData().catch(console.error)});
function parseCSV(text){const rows=[];let row=[],cell="",quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++;continue}if(c==='"'){quote=!quote;continue}if(c===","&&!quote){row.push(cell);cell="";continue}if((c==="\n"||c==="\r")&&!quote){if(cell||row.length){row.push(cell);rows.push(row);row=[];cell=""}if(c==="\r"&&n==="\n")i++;continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function toNumber(v){return Number(String(v??"").replace(/\s/g,"").replace("%","").replace(",","."))||0}
function toDate(v){const s=String(v??"").trim();const m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]));return new Date(s)}
function formatNumber(v,d=2){return Number(v).toFixed(d).replace(".",",")}
function formatCount(v){return Number(v).toLocaleString("fr-FR")}
function dateLabel(d){return d.toLocaleDateString("fr-FR",{day:"2-digit",month:"short",year:"numeric"}).replace(".","")}
async function loadData(){const r=await fetch(CSV_URL,{cache:"no-store"});const parsed=parseCSV(await r.text());parsed.shift();const rows=parsed.filter(x=>x[0]).map(x=>({date:toDate(x[0]),result:String(x[6]||"").trim().toUpperCase(),odd:toNumber(x[5]),profit:toNumber(x[7])})).filter(x=>!isNaN(x.date)).sort((a,b)=>a.date-b.date);renderStats(rows);renderDailyChart(rows)}
function renderStats(rows){const total=rows.length,wins=rows.filter(r=>r.result.includes("WIN")).length,profit=rows.reduce((s,r)=>s+r.profit,0),avg=total?rows.reduce((s,r)=>s+r.odd,0)/total:0,roi=total?(profit/total)*100:0;profitTotal.textContent=`${profit>=0?"+":""}${formatNumber(profit,2)}u`;winRate.textContent=`${formatNumber(wins/total*100,2)}%`;document.getElementById("roi").textContent=`${formatNumber(roi,2)}%`;numberTips.textContent=formatCount(total);averageOdds.textContent=formatNumber(avg,2)}
function renderDailyChart(rows){let cum=0;const labels=[],values=[],years=[];rows.forEach(r=>{cum+=r.profit;labels.push(dateLabel(r.date));values.push(Number(cum.toFixed(2)));years.push(r.date.getFullYear())});const lastValue=values[values.length-1];const yearTicks=new Set();years.forEach((year,i)=>{if(!yearTicks.has(year))yearTicks.add(year)});const firstIndexByYear={};years.forEach((year,i)=>{if(firstIndexByYear[year]===undefined)firstIndexByYear[year]=i});const lastPointLabelPlugin={id:"lastPointLabel",afterDatasetsDraw(chart){const{ctx}=chart,meta=chart.getDatasetMeta(0),last=meta.data[meta.data.length-1];if(!last)return;ctx.save();ctx.font="700 18px Fira Code, monospace";ctx.fillStyle="#10100E";ctx.textAlign="right";ctx.textBaseline="bottom";ctx.fillText(`${lastValue>=0?"+":""}${lastValue.toFixed(2).replace(".",",")}u`,last.x-8,last.y-14);ctx.restore()}};const ctx=document.getElementById("dailyChart");if(chartInstance)chartInstance.destroy();chartInstance=new Chart(ctx,{type:"line",data:{labels,datasets:[{label:"Profit cumulé",data:values,borderColor:"#123B2A",borderWidth:2,pointRadius:0,pointHoverRadius:4,pointHitRadius:12,tension:0,fill:false}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},animation:false,layout:{padding:{top:34,right:28,bottom:8,left:0}},plugins:{legend:{display:false},tooltip:{enabled:true,backgroundColor:"#10100E",titleColor:"#F4EFE4",bodyColor:"#F4EFE4",displayColors:false,padding:12,callbacks:{title:(items)=>items&&items.length?items[0].label:"",label:(c)=>`Plus-value : ${c.parsed.y>=0?"+":""}${c.parsed.y.toFixed(2).replace(".",",")}u`}}},scales:{x:{grid:{display:false},ticks:{color:"#726D65",font:{family:"Fira Code",size:13,weight:"500"},autoSkip:false,maxRotation:0,minRotation:0,callback:function(value,index){const year=years[index];return firstIndexByYear[year]===index?String(year):""}},border:{display:false}},y:{grid:{color:"#D6CEC1"},ticks:{display:false},border:{display:false}}}},plugins:[lastPointLabelPlugin]})}
